### PR TITLE
Yoda conditionals are ugly

### PR DESCRIPTION
**Pull request by TyOverby**

### CODE REVIEW

**Comment by cartermp** [comment]
yoda conitionals are more efficient in C#, hence their use

**Comment by TyOverby** [comment]
> yoda conitionals are more efficient in C#, hence their use

This is fake news.  I'm going to post this on twitter and get people to bombard you with thumbs down.

**Comment by cartermp** [comment]
Yoder conditionuhls compile down to octal which is obvi more efficient

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TyOverby** [comment]
I'll have you know that I am a programming languages expert, and that means that I'm always right.  Here are some words to convince you:

* cartesian closed
* category of categories
* comonad
* contravariant functor
* essentially surjective

**Comment by cartermp** [comment]
> not even mentioning pure type systems
> no higher sorted kinds
> no lambda cube

But you did mention some good words.  You're cool

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cartermp** [comment]
And by cool I mean cool like me

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cartermp** [comment]
We are cool as cucumbers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
